version: '3'
services:
  db:
    image: mysql:8.0.22
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
    ports:
      - '3306:3306'

  web:
    tty: true
    stdin_open: true
    build: .
    command: 
      ["bash", "-c", "rm -f tmp/pids/server.pid; \
      bundle exec rake db:create; \
      bundle exec rake db:migrate:reset RAILS_ENV=development; \
      bundle exec rake db:seed; \
      bundle exec rails s -p 3000 -b '0.0.0.0';"]      
    volumes:
      - .:/app
    ports:
      - '80:3000'
    links:
      - db